image: etiennebinginot/agora:1.2

stages:
  - factory
  - sixqp
  - splendor
  - deploy

cache:
  paths:
    - /app/vendor/


variables:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_TCP_PORT: 3307
  MYSQL_DATABASE: main_test
  XDEBUG_MODE: coverage

services:
  - name: mariadb:10.11.2
    alias: database_test


before_script:
  - symfony console --env=test doctrine:migrations:migrate
  - symfony console doctrine:fixtures:load --env=test -n

  

deploy_dev_game:
  stage: deploy
  environment:
    name: staging
    url: http://srv-dpi-agora-dev-jeux.univ-rouen.fr/
  script:
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo $ID_RSA_GAME | base64 -d)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $SERVER_GAME_USER@$SERVER_GAME_IP "cd /var/www/agora && git checkout develop-game && git pull origin develop-game && docker compose up --build -d && exit"
  only:
    - develop-game

unitFactory:
  stage: factory
  script:
    - php bin/phpunit tests/Game/Factory/Unit --coverage-text
  allow_failure: false
  environment: test

integrationFactory:
  stage: factory
  only:
    - develop-game
    - preprod
    - main
  script:
    - php bin/phpunit tests/Game/Factory/Integration --coverage-text
  allow_failure: false
  environment: test

unit6QP:
  stage: sixqp
  script:
    - php bin/phpunit tests/Game/SixQP/Unit --coverage-text
  allow_failure: false
  environment: test

integration6QP:
  stage: sixqp
  only:
    - develop-game
    - preprod
    - main
  script:
    - php bin/phpunit tests/Game/SixQP/Integration --coverage-text
  allow_failure: false
  environment: test

application6QP:
  stage: sixqp
  only:
    - develop-game
    - preprod
    - main
  script:
    - symfony console tailwind:build
    - php bin/phpunit tests/Game/SixQP/Application --coverage-text
  allow_failure: false
  environment: test

unitSplendor:
  stage: splendor
  script:
    - php bin/phpunit tests/Game/Splendor/Unit --coverage-text
  allow_failure: false
  environment: test

integrationSplendor:
  stage: splendor
  only:
    - develop-game
    - preprod
    - main
  script:
    - php bin/phpunit tests/Game/Splendor/Integration --coverage-text
  allow_failure: false
  environment: test


