
image: php:8.3-apache


services:
  - name: mariadb:10.11.2
    alias: database_test

before_script:
  - apt-get -y update && apt-get -y install \
    git \
    zip \
    unzip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get -y autoremove
  - curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash \
    && apt install symfony-cli
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - docker-php-ext-install pdo_mysql opcache
  - docker-php-ext-enable pdo_mysql opcache

variables:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_TCP_PORT: 3307
  MYSQL_DATABASE: main_test


build:
  stage: build
  cache:
    key: dependance
    paths:
      - vendor/
    policy: push
  script:
    - php composer.phar install


unit:
  stage: test
  cache:
    key: dependance
    paths:
      - vendor/
    policy: pull
  script:
    - php bin/phpunit tests/Unit --coverage-text
  allow_failure: false
  environment: test

integration:
  stage: test
  cache:
    key: dependance
    paths:
      - vendor/
    policy: pull
  script:
    - symfony console doctrine:migrations:migrate
    - symfony console --env=test doctrine:migrations:migrate
    - php bin/phpunit tests/Integration --coverage-text
  allow_failure: false
  environment: test
