
image: jakzal/phpqa:php8.3

before_script:
  - composer install
  - docker-php-ext-install pdo_mysql

cache:
  paths:
    - vendor/

stages:
  - UnitTests
  - IntegrationTests

local:
  stage: UnitTests
  only:
    - develop
  script:
    - php bin/phpunit tests/Unit
  allow_failure: false

develop:
  stage: IntegrationTests
  image: mariadb:10.11.2
  variables:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: main_test
    MYSQL_USER: root
    MYSQL_PASSWORD: password
    MYSQL_URL: mysql://root:password@database_test:3307/main?serverVersion=10.11.2-MariaDB&charset=utf8mb4
  script:
    - php bin/phpunit tests/Integration
  allow_failure: false
