
image: jakzal/phpqa:php8.3

before_script:
  - composer install

cache:
  paths:
    - vendor/

stages:
  - UnitTests
  - IntegrationTests

local:
  stage: UnitTests
  script:
    - php bin/phpunit tests/Unit
  allow_failure: false

develop:
  stage: IntegrationTests
  only:
    - develop
  services:
    - name: mariadb:10.3.11
      alias: db
  variables:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: main_test
    MYSQL_USER: root
    MYSQL_PASSWORD: password
    MYSQL_URL: mysql://root:password@database:3306/main?serverVersion=10.11.2-MariaDB&charset=utf8mb4
  script:
    - php bin/phpunit tests/Integration
  allow_failure: false
