
image: php:8.3-apache

cache:
  paths:
    - vendor/

before_script:
  - apt-get -y update && apt-get -y install \
    git \
    zip \
    unzip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get -y autoremove
  - curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash \
    && apt install symfony-cli
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - docker-php-ext-install pdo_mysql opcache
  - docker-php-ext-enable pdo_mysql opcache
  - php composer.phar install

services:
  - mariadb:10.11.2

variables:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_TCP_PORT: 3307
  MYSQL_DATABASE: main_test




stages:
  - UnitTests
  - IntegrationTests

local:
  stage: UnitTests
  script:
    - php bin/phpunit tests/Unit --coverage-text
  allow_failure: false

develop:
  stage: IntegrationTests
  script:
    - php bin/phpunit tests/Integration --coverage-text
  allow_failure: false
