image: etiennebinginot/agora:1.0

variables:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_TCP_PORT: 3307
  MYSQL_DATABASE: main_test

cache:
  policy: pull-push
  unprotect: true
  untracked: true
  when: on_success

services:
  - name: mariadb:10.11.2
    alias: database_test


before_script:
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$ID_RSA_GAME")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  

deploy_dev_game:
  stage: deploy
  environment:
    name: staging
    url: https://srv-dpi-agora-dev-jeux.univ-rouen.fr/
  script:
    - ssh $SERVER_GAME_USER@$SERVER_GAME_IP "cd var/www/agora && git checkout develop-game && git pull origin develop-game && docker-compose up --build && exit"
  only:
    - develop-game

unit:
  stage: test
  script:
    - php bin/phpunit tests/Unit --coverage-text
  allow_failure: false
  environment: test

integration:
  stage: test
  only:
    - develop-game
    - preprod
    - main
  script:
    - symfony console --env=test doctrine:migrations:migrate
    - symfony console doctrine:fixtures:load --env=test -n
    - php bin/phpunit tests/Integration --coverage-text
  allow_failure: false
  environment: test