version: '3'

services:
  agora:
    command: bash -c "cd /app
      && symfony console doctrine:migrations:migrate
      && symfony console --env=test doctrine:migrations:migrate
      && composer update
      && symfony server:stop
      && symfony server:start"
    volumes:
      - .:/app
      - /app/vendor
      - /app/var
    ports:
      - "8000:8000"

###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###

###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "80"
###< symfony/mercure-bundle ###

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:apache
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8081:80"