version: '3'

services:
  agora:
    command: bash -c "cd /app
      && symfony console doctrine:migrations:migrate
      && symfony console --env=test doctrine:migrations:migrate
      && symfony console importmap:install
      && (php bin/console tailwind:build --watch &)
      && frankenphp run --config /etc/caddy/Caddyfile --watch"
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_DEBUG: 1
      APP_ENV_SERVER: gametest
      MERCURE_PUBLIC_URL: https://${SERVER_DEV_GAME_IP}/.well-known/mercure


###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
