agora_game_homepage_spldr:
    path:     /splendor/{gameId}
    defaults: { _controller: AGORAGameSplendorBundle:Default:index, gameId: "1" }

agora_game_create_spldr:
    path: /game/create/spldr
    defaults: { _controller: AGORAGameSplendorBundle:Default:create }

agora_game_join_spldr:
    path: /game/join/spldr/{gameId}
    defaults: { _controller: AGORAGameSplendorBundle:Default:join, gameId: "1" }

agora_game_quit_spldr:
  path: /game/quit/spldr/{gameId}
  defaults: { _controller: AGORAGameSplendorBundle:Default:quit }

agora_game_delete_spldr:
    path: /game/delete/spldr/{gameId}
    defaults: { _controller: AGORAGameSplendorBundle:Default:delete, gameId: "1" }