services:
    agora_game.game:
        class: AGORA\Game\GameBundle\Service\GameService
        arguments: ["@doctrine.orm.entity_manager"]
        public: true

    agora_game.splendor:
        class: AGORA\Game\SplendorBundle\Service\SplendorService
        arguments: ["@doctrine.orm.entity_manager", "@agora_game.game"]

    agora_game.splendorLog:
        class: AGORA\Game\SplendorBundle\Service\SplendorLogService
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: splendorSocket }

