services:
  agora_game.game:
    class: AGORA\Game\GameBundle\Service\GameService
    arguments: ["@doctrine.orm.entity_manager"]
    public: true

  agora_game.azul:
    class: AGORA\Game\AzulBundle\Service\AzulService
    arguments: ["@doctrine.orm.entity_manager", "@agora_game.game"]
    public: true

  agora_game.azulLog:
    class: AGORA\Game\AzulBundle\Service\AzulLogService
    arguments: ['@logger']
    tags:
      - { name: monolog.logger, channel: azulSocket }