services:
    agora_game.game:
        class: AGORA\Game\GameBundle\Service\GameService
        arguments: ["@doctrine.orm.entity_manager"]
        public: true

    agora_game.ave_cesar:
        class: AGORA\Game\AveCesarBundle\Service\AveCesarService
        arguments: ["@doctrine.orm.entity_manager", "@agora_game.game"]

    agora_game.ave_cesar_log:
        class: AGORA\Game\AveCesarBundle\Service\AveCesarLogService
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: aveCesarAndChatSocket }

