
agora_game_create_p4:
  path: /create
  defaults: { _controller: AGORAGamePuissance4Bundle:Default:createGame }

agora_game_join_p4:
  path: /join/{gameId}
  defaults: { _controller: AGORAGamePuissance4Bundle:Default:joinGame }

agora_game_homepage_p4:
  path: /play/{gameId}
  defaults: { _controller: AGORAGamePuissance4Bundle:Default:play }

agora_game_quit_p4:
  path: /quit/{gameId}
  defaults: { _controller: AGORAGamePuissance4Bundle:Default:quit }

agora_game_delete_p4:
  path: /delete/{gameId}
  defaults: { _controller: AGORAGamePuissance4Bundle:Default:delete, gameId: "8" }
