services:
    agora_game.game:
        class: AGORA\Game\GameBundle\Service\GameService
        arguments: ["@doctrine.orm.entity_manager"]
        public: true

    agora_game.morpion:
        class: AGORA\Game\MorpionBundle\Service\MorpionService
        arguments: ["@doctrine.orm.entity_manager", "@agora_game.game"]
        public: true
        
    agora_game.morpionLog:
        class: AGORA\Game\MorpionBundle\Service\MorpionLogService
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: morpionSocket }