agora_game_create_sqp:
    path: /create
    defaults: { _controller: AGORAGameSQPBundle:Default:createLobby }

agora_game_join_sqp:
    path: /join/{gameId}
    defaults: { _controller: AGORAGameSQPBundle:Default:joinLobby, gameId: "1" }

agora_game_homepage_sqp:
    path: /play/{gameId}
    defaults: { _controller: AGORAGameSQPBundle:Default:play }

agora_game_quit_sqp:
  path: /quit/{gameId}
  defaults: { _controller: AGORAGameSQPBundle:Default:quit }

agora_game_delete_sqp:
    path: /delete/{gameId}
    defaults: { _controller: AGORAGameSQPBundle:Default:delete, gameId: "1" }