services:
    agora_game.game:
        class: AGORA\Game\GameBundle\Service\GameService
        arguments: ["@doctrine.orm.entity_manager"]
        public: true

    agora_game_sqp.sqpapi:
        class: AGORA\Game\SQPBundle\Model\SQPAPI
        arguments: ["@doctrine.orm.entity_manager", "@agora_game.game"]
        
    agora_game_sqp.sqpLog:
        class: AGORA\Game\SQPBundle\Service\SqpLogService
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: sqpSocket }
